### ISSUE TITLE
sorry for the question, but

### ISSUE THREAD

**Issue by philsrfn** [CramMK/dots#2]
but my emacs config isnt working i copied the init file over to .emacs.d, but when i do like emacs dev/setup.py, there is just this blank screen, es hat eine schöne farbe, aber es ist nicht benutzbar, ich kann es auch nicht schließen mit super + shift + q

**Comment by marcothms** [comment]
Da ich mein emacs taeglich fuer die Uni benutze, kann ich bestaetigen, dass es funktioniert. Hast du denn alle Pakete runterladen und kompilieren lassen, welche mein emacs benutzt? (Das recht viele.) Sollte einfach erkennbar sein, wenn du unten links in die Statusbar schaust.
